# Generated by Django 4.1.3 on 2023-05-17 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 5, 17)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.TimeField(default=datetime.time(14, 44, 12, 53646)),
        ),
    ]
