# Generated by Django 4.1.3 on 2023-04-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanban',
            options={'verbose_name_plural': 'Канбаны'},
        ),
    ]
