# Generated by Django 4.1.3 on 2023-05-10 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_time',
            field=models.TimeField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(default=datetime.time(16, 24, 54, 559541)),
        ),
        migrations.AlterField(
            model_name='task',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.kanban'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='new', max_length=100),
        ),
    ]
