# Generated by Django 4.1.3 on 2023-05-17 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0002_alter_task_created_date_alter_task_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.TimeField(default=datetime.time(15, 32, 37, 76134)),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='исполнитель'),
        ),
    ]
