# Generated by Django 4.1.3 on 2023-05-10 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_task_completed_date_alter_task_completed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(default=datetime.time(16, 28, 12, 951972)),
        ),
    ]
