# Generated by Django 4.1.3 on 2023-05-10 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_task_created_date_alter_task_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_time',
            field=models.TimeField(default=datetime.time(16, 32, 50, 546701)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.TimeField(default=datetime.time(16, 32, 50, 546701)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(default=datetime.time(16, 32, 50, 546701)),
        ),
    ]
