# Generated by Django 4.2 on 2023-05-27 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_task_created_time_alter_task_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 5, 27)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.TimeField(default=datetime.time(9, 51, 17, 866682)),
        ),
    ]
