# Generated by Django 4.1.3 on 2023-05-10 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_task_assigned_date_alter_task_assigned_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_time',
            field=models.TimeField(default=datetime.time(16, 43, 30, 385633)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.TimeField(default=datetime.time(16, 43, 30, 385633)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(default=datetime.time(16, 43, 30, 385633)),
        ),
    ]
